version: "2.4"
services:
  weston:
    # The environment variable CT_TAG_DEBIAN is set in TorizonCore
    # as explained on https://developer.toradex.com/knowledge-base/container-tags-and-versioning
    image: torizon/weston-vivante:${CT_TAG_WESTON_VIVANTE}
    network_mode: host
    environment:
      - ACCEPT_FSL_EULA=1
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /run/udev
        target: /run/udev
      - type: bind
        source: /dev
        target: /dev
    cap_add:
      - CAP_SYS_TTY_CONFIG
    # Add device access rights through cgroup...
    device_cgroup_rules:
      # ... for tty0
      - 'c 4:0 rmw'
      # ... for tty7
      - 'c 4:7 rmw'
      # ... for /dev/input devices
      - 'c 13:* rmw'
      - 'c 199:* rmw'
      # ... for /dev/dri devices
      - 'c 226:* rmw'
      - 'c 81:* rmw'

  pysimplegui:
    depends_on:
      - weston
    image: leonardoheldattoradex/pysimplegui
    user: torizon
    volumes:
      - '/tmp:/tmp'
